local LSM = LibStub('LibSharedMedia-3.0')

LSM:Register('statusbar', 'Asphyxia', [[Interface\AddOns\DSM\Media\StatusBars\Asphyxia]])
LSM:Register('statusbar', 'Bezo', [[Interface\AddOns\DSM\Media\StatusBars\Bezo]])
LSM:Register('statusbar', 'Dajova', [[Interface\AddOns\DSM\Media\StatusBars\Dajova]])
LSM:Register('statusbar', 'Duffed', [[Interface\AddOns\DSM\Media\StatusBars\Duffed]])
LSM:Register('statusbar', 'Flatt', [[Interface\AddOns\DSM\Media\StatusBars\Flatt]])
LSM:Register('statusbar', 'Sinaris', [[Interface\AddOns\DSM\Media\StatusBars\Sinaris]])
LSM:Register('statusbar', 'Slate', [[Interface\AddOns\DSM\Media\StatusBars\Slate]])
LSM:Register('statusbar', 'Smooth', [[Interface\AddOns\DSM\Media\StatusBars\Smooth]])
LSM:Register('statusbar', 'Tukui', [[Interface\AddOns\DSM\Media\StatusBars\Tukui]])

LSM:Register('statusbar', 'Aluminium Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Aluminium]])
LSM:Register('statusbar', 'Asphyxia Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Asphyxia]])
LSM:Register('statusbar', 'BantoBar Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\BantoBar]])
LSM:Register('statusbar', 'Button Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Button]])
LSM:Register('statusbar', 'Cloud Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Cloud]])
LSM:Register('statusbar', 'Comet Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Comet]])
LSM:Register('statusbar', 'Dabs Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Dabs]])
LSM:Register('statusbar', 'ElvUI Gloss Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\ElvUI]])
LSM:Register('statusbar', 'Falumn Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Falumn]])
LSM:Register('statusbar', 'Flat Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Flat]])
LSM:Register('statusbar', 'Frost Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Frost]])
LSM:Register('statusbar', 'Glamour Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour]])
LSM:Register('statusbar', 'Glamour2 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour2]])
LSM:Register('statusbar', 'Glamour3 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour3]])
LSM:Register('statusbar', 'Glamour4 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour4]])
LSM:Register('statusbar', 'Glamour5 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour5]])
LSM:Register('statusbar', 'Glamour6 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour6]])
LSM:Register('statusbar', 'Glamour7 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour7]])
LSM:Register('statusbar', 'Glaze Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glaze]])
LSM:Register('statusbar', 'Glaze2 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glaze2]])
LSM:Register('statusbar', 'Gloss Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Gloss]])
LSM:Register('statusbar', 'Healbot Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Healbot]])
LSM:Register('statusbar', 'LiteStep Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\LiteStep]])
LSM:Register('statusbar', 'Lyfe Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Lyfe]])
LSM:Register('statusbar', 'Minimalist Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Minimalist]])
LSM:Register('statusbar', 'Otravi Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Otravi]])
LSM:Register('statusbar', 'Outline Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Outline]])
LSM:Register('statusbar', 'Perl Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Perl]])
LSM:Register('statusbar', 'Rocks Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Rocks]])
LSM:Register('statusbar', 'Round Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Round]])
LSM:Register('statusbar', 'Ruben Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Ruben]])
LSM:Register('statusbar', 'Runes Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Runes]])
LSM:Register('statusbar', 'Sinaris Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Sinaris]])
LSM:Register('statusbar', 'Slate Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Slate]])
LSM:Register('statusbar', 'Smooth Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Smooth]])
LSM:Register('statusbar', 'Tukui Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Tukui]])
LSM:Register('statusbar', 'Water Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Water]])

LSM:Register('font', 'Big Noodle Titling', [[Interface\AddOns\DSM\Media\Fonts\BigNoodleTitling.ttf]])
LSM:Register('font', 'Dajova', [[Interface\AddOns\DSM\Media\Fonts\Dajova.ttf]])
LSM:Register('font', 'Oswald Bold', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Bold.ttf]])
LSM:Register('font', 'Oswald Light', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Light.ttf]])
LSM:Register('font', 'Oswald Regular', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Regular.ttf]])
LSM:Register('font', 'Saarland', [[Interface\AddOns\DSM\Media\Fonts\Saarland.ttf]])
LSM:Register('font', 'Samson', [[Interface\AddOns\DSM\Media\Fonts\Samson.ttf]])
LSM:Register('font', 'Sony Sketch', [[Interface\AddOns\DSM\Media\Fonts\SonySketch.ttf]])
LSM:Register('font', 'PT Sans Narrow Bold', [[Interface\AddOns\DSM\Media\Fonts\PTSansNarrow-Bold.ttf]])
LSM:Register('font', 'Diediedie', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]])
LSM:Register('font', 'Visitor TT2 BRK', [[Interface\AddOns\DSM\Media\Fonts\Visitor.ttf]])
LSM:Register('font', 'Homespun TT BRK', [[Interface\AddOns\DSM\Media\Fonts\Homespun.ttf]])
LSM:Register('font', 'Action Man', [[Interface\AddOns\DSM\Media\Fonts\ActionMan.ttf]])
LSM:Register('font', 'Continuum Medium', [[Interface\AddOns\DSM\Media\Fonts\ContinuumMedium.ttf]])
LSM:Register('font', 'Arial', [[Interface\AddOns\DSM\Media\Fonts\Arial.ttf]])
LSM:Register('font', 'KGSmallTownSouthernGirl', [[Interface\AddOns\DSM\Media\Fonts\KGSmallTownSouthernGirl.ttf]])
LSM:Register('font', 'Youthanasia Texture', [[Interface\AddOns\DSM\Media\Fonts\YOUTHAN.ttf]])
LSM:Register('font', 'Youthanasia Texture Regular', [[Interface\AddOns\DSM\Media\Fonts\YOUTTX.ttf]])
LSM:Register('font', 'Good Time', [[Interface\AddOns\DSM\Media\Fonts\GOODTIME.ttf]])
LSM:Register('font', 'Reprise Title', [[Interface\AddOns\DSM\Media\Fonts\Reprise Title.ttf]])
LSM:Register('font', 'Futurapress', [[Interface\AddOns\DSM\Media\Fonts\Futurapress.ttf]])
LSM:Register('font', 'Event Horizon', [[Interface\AddOns\DSM\Media\Fonts\Event Horizon.ttf]])
LSM:Register('font', 'H.H. Samuel', [[Interface\AddOns\DSM\Media\Fonts\H.H. Samuel.ttf]])
LSM:Register('sound', 'Warning', [[Interface\AddOns\DSM\Media\Media\Sounds\Warning.mp3]])

LSM:Register('font', 'Tukui Pixel', [[Interface\AddOns\DSM\Media\Fonts\Visitor.ttf]])
LSM:Register('font', 'Tukui Combat', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]])
LSM:Register('font', 'Tukui UnitFrame', [[Interface\AddOns\DSM\Media\Fonts\BigNoodleTitling.ttf]])

if not select(4, GetAddOnInfo('ElvUI')) then
	LSM:Register('font', 'ElvUI Alt-Combat', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]])
	LSM:Register('font', 'ElvUI Alt-Font', [[Interface\AddOns\DSM\Media\Fonts\ContinuumMedium.ttf]])
	LSM:Register('font', 'ElvUI Combat', [[Interface\AddOns\DSM\Media\Fonts\ActionMan.ttf]])
	LSM:Register('font', 'ElvUI Font', [[Interface\AddOns\DSM\Media\Fonts\PTSansNarrow-Bold.ttf]])
	LSM:Register('font', 'ElvUI Pixel', [[Interface\AddOns\DSM\Media\Fonts\Homespun.ttf]])
	LSM:Register('statusbar', 'ElvUI Gloss', [[Interface\AddOns\DSM\Media\StatusBars\ElvUI]])
end
