local LSM = LibStub('LibSharedMedia-3.0')
local AddOnName = ...
local Path = [[Interface\AddOns\]]..AddOnName..[[\Media\]]

LSM:Register('statusbar', 'Asphyxia', Path..[[StatusBars\Asphyxia]])
LSM:Register('statusbar', 'Bezo', Path..[[StatusBars\Bezo]])
LSM:Register('statusbar', 'Dajova', Path..[[StatusBars\Dajova]])
LSM:Register('statusbar', 'Duffed', Path..[[StatusBars\Duffed]])
LSM:Register('statusbar', 'ElvUI', Path..[[StatusBars\ElvUI]])
LSM:Register('statusbar', 'Flatt', Path..[[StatusBars\Flatt]])
LSM:Register('statusbar', 'Sinaris', Path..[[StatusBars\Sinaris]])
LSM:Register('statusbar', 'Slate', Path..[[StatusBars\Slate]])
LSM:Register('statusbar', 'Smooth', Path..[[StatusBars\Smooth]])
LSM:Register('statusbar', 'Tukui', Path..[[StatusBars\Tukui]])

LSM:Register('statusbar', 'Aluminium Vertical', Path..[[StatusBars\Vertical\Aluminium]])
LSM:Register('statusbar', 'Asphyxia Vertical', Path..[[StatusBars\Vertical\Asphyxia]])
LSM:Register('statusbar', 'BantoBar Vertical', Path..[[StatusBars\Vertical\BantoBar]])
LSM:Register('statusbar', 'Button Vertical', Path..[[StatusBars\Vertical\Button]])
LSM:Register('statusbar', 'Cloud Vertical', Path..[[StatusBars\Vertical\Cloud]])
LSM:Register('statusbar', 'Comet Vertical', Path..[[StatusBars\Vertical\Comet]])
LSM:Register('statusbar', 'Dabs Vertical', Path..[[StatusBars\Vertical\Dabs]])
LSM:Register('statusbar', 'Dajova Vertical', Path..[[StatusBars\Vertical\Dajova]])
LSM:Register('statusbar', 'Duffed Vertical', Path..[[StatusBars\Vertical\Duffed]])
LSM:Register('statusbar', 'ElvUI Gloss Vertical', Path..[[StatusBars\Vertical\ElvUI]])
LSM:Register('statusbar', 'Falumn Vertical', Path..[[StatusBars\Vertical\Falumn]])
LSM:Register('statusbar', 'Flat Vertical', Path..[[StatusBars\Vertical\Flat]])
LSM:Register('statusbar', 'Frost Vertical', Path..[[StatusBars\Vertical\Frost]])
LSM:Register('statusbar', 'Glamour Vertical', Path..[[StatusBars\Vertical\Glamour]])
LSM:Register('statusbar', 'Glamour2 Vertical', Path..[[StatusBars\Vertical\Glamour2]])
LSM:Register('statusbar', 'Glamour3 Vertical', Path..[[StatusBars\Vertical\Glamour3]])
LSM:Register('statusbar', 'Glamour4 Vertical', Path..[[StatusBars\Vertical\Glamour4]])
LSM:Register('statusbar', 'Glamour5 Vertical', Path..[[StatusBars\Vertical\Glamour5]])
LSM:Register('statusbar', 'Glamour6 Vertical', Path..[[StatusBars\Vertical\Glamour6]])
LSM:Register('statusbar', 'Glamour7 Vertical', Path..[[StatusBars\Vertical\Glamour7]])
LSM:Register('statusbar', 'Glaze Vertical', Path..[[StatusBars\Vertical\Glaze]])
LSM:Register('statusbar', 'Glaze2 Vertical', Path..[[StatusBars\Vertical\Glaze2]])
LSM:Register('statusbar', 'Gloss Vertical', Path..[[StatusBars\Vertical\Gloss]])
LSM:Register('statusbar', 'Healbot Vertical', Path..[[StatusBars\Vertical\Healbot]])
LSM:Register('statusbar', 'LiteStep Vertical', Path..[[StatusBars\Vertical\LiteStep]])
LSM:Register('statusbar', 'Lyfe Vertical', Path..[[StatusBars\Vertical\Lyfe]])
LSM:Register('statusbar', 'Minimalist Vertical', Path..[[StatusBars\Vertical\Minimalist]])
LSM:Register('statusbar', 'Otravi Vertical', Path..[[StatusBars\Vertical\Otravi]])
LSM:Register('statusbar', 'Outline Vertical', Path..[[StatusBars\Vertical\Outline]])
LSM:Register('statusbar', 'Perl Vertical', Path..[[StatusBars\Vertical\Perl]])
LSM:Register('statusbar', 'Rocks Vertical', Path..[[StatusBars\Vertical\Rocks]])
LSM:Register('statusbar', 'Round Vertical', Path..[[StatusBars\Vertical\Round]])
LSM:Register('statusbar', 'Ruben Vertical', Path..[[StatusBars\Vertical\Ruben]])
LSM:Register('statusbar', 'Runes Vertical', Path..[[StatusBars\Vertical\Runes]])
LSM:Register('statusbar', 'Sinaris Vertical', Path..[[StatusBars\Vertical\Sinaris]])
LSM:Register('statusbar', 'Slate Vertical', Path..[[StatusBars\Vertical\Slate]])
LSM:Register('statusbar', 'Smooth Vertical', Path..[[StatusBars\Vertical\Smooth]])
LSM:Register('statusbar', 'Tukui Vertical', Path..[[StatusBars\Vertical\Tukui]])
LSM:Register('statusbar', 'Water Vertical', Path..[[StatusBars\Vertical\Water]])

LSM:Register('font', 'Action Man', Path..[[Fonts\ActionMan.ttf]])
LSM:Register('font', 'Arial', Path..[[Fonts\Arial.ttf]])
LSM:Register('font', 'Big Noodle Titling', Path..[[Fonts\BigNoodleTitling.ttf]])
LSM:Register('font', 'Continuum Medium', Path..[[Fonts\ContinuumMedium.ttf]])
LSM:Register('font', 'Dajova', Path..[[Fonts\Dajova.ttf]])
LSM:Register('font', 'Diediedie', Path..[[Fonts\Diediedie.ttf]])
LSM:Register('font', 'Event Horizon', Path..[[Fonts\Event Horizon.ttf]])
LSM:Register('font', 'Futurapress', Path..[[Fonts\Futurapress.ttf]])
LSM:Register('font', 'Good Time', Path..[[Fonts\GOODTIME.ttf]])
LSM:Register('font', 'H.H. Samuel', Path..[[Fonts\H.H. Samuel.ttf]])
LSM:Register('font', 'Homespun TT BRK', Path..[[Fonts\Homespun.ttf]])
LSM:Register('font', 'KGSmallTownSouthernGirl', Path..[[Fonts\KGSmallTownSouthernGirl.ttf]])
LSM:Register('font', 'Oswald Bold', Path..[[Fonts\Oswald-Bold.ttf]])
LSM:Register('font', 'Oswald Light', Path..[[Fonts\Oswald-Light.ttf]])
LSM:Register('font', 'Oswald Regular', Path..[[Fonts\Oswald-Regular.ttf]])
LSM:Register('font', 'PT Sans Narrow', Path..[[Fonts\PT_Sans_Narrow.ttf]])
LSM:Register('font', 'PT Sans Narrow Bold', Path..[[Fonts\PTSansNarrow-Bold.ttf]])
LSM:Register('font', 'Reprise Title', Path..[[Fonts\Reprise Title.ttf]])
LSM:Register('font', 'Saarland', Path..[[Fonts\Saarland.ttf]])
LSM:Register('font', 'Samson', Path..[[Fonts\Samson.ttf]])
LSM:Register('font', 'Sony Sketch', Path..[[Fonts\SonySketch.ttf]])
LSM:Register('font', 'Visitor TT2 BRK', Path..[[Fonts\Visitor.ttf]])
LSM:Register('font', 'Youthanasia Texture Regular', Path..[[Fonts\YOUTTX.ttf]])
LSM:Register('font', 'Youthanasia Texture', Path..[[Fonts\YOUTHAN.ttf]])

LSM:Register('sound', 'Warning', Path..[[Media\Sounds\Warning.mp3]])

LSM:Register('font', 'Tukui Combat', Path..[[Fonts\Diediedie.ttf]])
LSM:Register('font', 'Tukui Pixel', Path..[[Fonts\Visitor.ttf]])
LSM:Register('font', 'Tukui UnitFrame', Path..[[Fonts\BigNoodleTitling.ttf]])

if not select(4, GetAddOnInfo('ElvUI')) then
	LSM:Register('font', 'ElvUI Alt-Combat', Path..[[Fonts\Diediedie.ttf]])
	LSM:Register('font', 'ElvUI Alt-Font', Path..[[Fonts\ContinuumMedium.ttf]])
	LSM:Register('font', 'ElvUI Combat', Path..[[Fonts\ActionMan.ttf]])
	LSM:Register('font', 'ElvUI Font', Path..[[Fonts\PTSansNarrow-Bold.ttf]])
	LSM:Register('font', 'ElvUI Pixel', Path..[[Fonts\Homespun.ttf]])

	LSM:Register('statusbar', 'ElvUI Gloss', Path..[[StatusBars\ElvUI]])
end
